version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: mc-frontend
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/minecraft-dashboard:/app
    depends_on:
      - backend
    networks:
      - frontend_net
      - minecraft_net